CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    contrasenia TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS categorias (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ingresos (
    id_ingreso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    descripcion TEXT NOT NULL,
    monto NUMERIC(18, 2) NOT NULL,
    fecha TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS gastos (
    id_gasto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    id_categoria INTEGER NOT NULL REFERENCES categorias(id_categoria),
    descripcion TEXT NOT NULL,
    monto NUMERIC(18, 2) NOT NULL,
    fecha TIMESTAMPTZ NOT NULL
);

INSERT INTO categorias (id_categoria, nombre)
VALUES
    (1, 'Alimentación'),
    (2, 'Transporte'),
    (3, 'Servicios'),
    (4, 'Entretenimiento'),
    (5, 'Salud'),
    (6, 'Educación')
ON CONFLICT (id_categoria) DO UPDATE SET nombre = EXCLUDED.nombre;

SELECT setval(
    pg_get_serial_sequence('categorias', 'id_categoria'),
    (SELECT MAX(id_categoria) FROM categorias)
);
